# Generated by Django 2.2.4 on 2019-10-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_rating_5'),
        ('user', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Books'),
        ),
    ]
